### PR TITLE
change datum default to MSL for coops_product_within_region

### PR DESCRIPTION
**Pull request by FariborzDaneshvar-NOAA**

### CODE REVIEW

**Comment by SorooshMani-NOAA** [comment]
@FariborzDaneshvar-NOAA the code in this repo is styled using black. Please install it and format the file you updated. Thank you!

**Comment by SorooshMani-NOAA** [comment]
@pmav99 I'd like to ask for your opinion on this:

We're changing the default datum for COOPS from STND to MSL, since it makes more sense for it to be MSL. One way to fix the tests is to add the explicit datum request to be STND in the tests, another is to update the test VCRs and refs to reflect the new default. Which one do you prefer? I think the first one is better.

Another thing is do we want to warn the user of this change when they don't pass any value for datum or not?

**Comment by SorooshMani-NOAA** [comment]
Actually we don't need to update the default in searvey ... let's just update the default in StormEvents for now, the we'll use the `MSL` default in the new COOPS API in searvey, that way we don't need to worry about warning the users of the change. @pmav99 @FariborzDaneshvar-NOAA what do you think?

**Comment by FariborzDaneshvar-NOAA** [comment]
> Actually we don't need to update the default in searvey ... let's just update the default in StormEvents for now, the we'll use the `MSL` default in the new COOPS API in searvey, that way we don't need to worry about warning the users of the change. @pmav99 @FariborzDaneshvar-NOAA what do you think?

@SorooshMani-NOAA whichever you think might raise less confusion. thanks

**Comment by SorooshMani-NOAA** [comment]
See https://github.com/oceanmodeling/searvey/issues/99#issuecomment-1908447540

**Pull request closed without merging**
