### PR TITLE
use "Orange Is The New Black" (`oitnb`) instead of `black` 

### PR DESCRIPTION
**Pull request by zacharyburnettNOAA**
I suggest we use `oitnb` (a fork of `black`) as I have found it is more flexible and has less errors than `black`

### CODE REVIEW

**Comment by pmav99** [comment]
AFAIK, the main difference/improvement between `oitnb` and similar forks/tools is using single instead of double quotes. 

I don't have particularly strong opinions on the subject, especially if the conversion/normalization happens automatically. Nevertheless, I am a bit concerned with the (lack of) traction that `oitnb` seems to have compared to black. 300+ contributors vs a project that is hosted on sourceforge. This is not a great guarantee for the future.

> has less errors than black

Could you elaborate a bit on that?

**Comment by zacharyburnettNOAA** [comment]
> > has less errors than black
> 
> Could you elaborate a bit on that?

sure thing, the current workflows are failing at the `black --check .` step:
https://github.com/oceanmodeling/searvey/runs/6065814525?check_suite_focus=true
```
  source .venv/bin/activate
  black --check
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.12/x64/lib
    VENV: .venv/bin/activate
Traceback (most recent call last):
  File "/home/runner/work/searvey/searvey/.venv/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/runner/work/searvey/searvey/.venv/lib/python3.9/site-packages/black/__init__.py", line 1372, in patched_main
    patch_click()
  File "/home/runner/work/searvey/searvey/.venv/lib/python3.9/site-packages/black/__init__.py", line 1358, in patch_click
    from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/work/searvey/searvey/.venv/lib/python3.9/site-packages/click/__init__.py)
Error: Process completed with exit code 1.
```
but the `oitnb --check .` step has no such errors:
https://github.com/oceanmodeling/searvey/runs/6066016203?check_suite_focus=true
```
  source .venv/bin/activate
  oitnb --check .
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.12/x64/lib
    VENV: .venv/bin/activate
All OK!
14 files would be left unchanged.

**Comment by brey** [comment]
@zacharyburnett @pmav99 Shall we keep it with `black` for now but try to use as less stringent configuration as possible?

**Comment by zacharyburnettNOAA** [comment]
> @zacharyburnett @pmav99 Shall we keep it with `black` for now but try to use as less stringent configuration as possible?

That is fine with me, is there a way to make the `black --check` step work in the automated workflow?

**Comment by pmav99** [comment]
Hi Zach

I finally found the time to have a closer look,. Nevertheless, I think that we should not merge this specific PR. 

The PR does several things, but the ones that I am skeptical about are:

1. the replacement of `black` with `oitnb` 
2. the reordering of imports using `isort`. 

As far as black goes, and as we discussed previously, I don't think that the `single` vs `double` quotes issue is important enough to switch to a barely supported project. 

Now as far as `isort` goes, we already use `reorder-python-imports` via `pre-commit`. 
https://github.com/oceanmodeling/searvey/blob/dee16933c5c2b2c4de1386bebef94b0e92dc163f/.pre-commit-config.yaml#L28-L33

`isort` is indeed more high-profile than `reorder-python-imports`. Nevertheless, `reorder-python-imports` does work, it is actively maintained and we already use it. I am not sure what exactly we gain by switching. Not to mention that we should also replace the pre-commit hook in order to avoid incompatibilities in the future.

As far as the issue you had with black, I think that the problem was the usage of an internal `click` API and that it has been resolved with the release of newer versions.

That being said, d041def should be merged. you can make a new PR if you want, or i can `cherry-pick` it and add it myself. Either way, you will remain the commit author.

**Comment by zacharyburnett** [comment]
sure thing, that sounds reasonable. I made a new pull request #21 and will close this one

**Pull request closed without merging**
