### PR TITLE
move `stormevents.coops` to `searvey.coops`

### PR DESCRIPTION
**Pull request by zacharyburnettNOAA**

### CODE REVIEW

**Comment by zacharyburnettNOAA** [comment]
I'm not really familiar with `poetry`, why is this failing?

```toml
[tool.poetry.dependencies]
python = "^3.9"
erddapy = "^1.1"
pandas = "^1.3"
pydantic = "^1.8"
requests = "^2.26"
beautifulsoup4 = "^4.11"
geopandas = "^0.10"
typepigeon = "^1"
xarray = "^2022.3"
shapely = "^1.8"
```
```
  Because searvey depends on Shapely (^1.8) which doesn't match any versions, version solving failed.
```
https://github.com/oceanmodeling/searvey/runs/6040339252?check_suite_focus=true

**Comment by pmav99** [comment]
> I'm not really familiar with `poetry`, why is this failing?
> 
> https://github.com/oceanmodeling/searvey/runs/6040339252?check_suite_focus=true

Hi Zach

In the "Files changed", there is an update in `pyproject.toml` but there are no changes in `poetry.lock`. This probably means that you edited `pyproject.toml` by hand and you didn't run `poetry update`. This is also hinted by this line: https://github.com/oceanmodeling/searvey/runs/6040339252?check_suite_focus=true#step:6:10

TBH, I haven't encountered this specific error before, and I do find it a bit confusing, but I suspect that what it actually means is that `shapely 1.8.1` does not match any version **in poetry.lock**, not in PyPI.

What you should do to resolve this is to run `poetry update` which will update the `poetry.lock` file *and* install the dependencies in your environment. You should then `git add poetry.lock` and commit that file too. This way, the CI should be able to install the correct dependencies. If not, ping me and I will try to have a closer look.

### `pyproject.toml` vs `poetry.lock`

The idea is that in `pyproject.toml` you specify the dependencies constraints, and `poetry`, after resolving the dependency graph, serializes the "solution" it came up with in `poetry.lock`. Upon installation, `poetry` uses `poetry.lock` to install the actual packages in the environment.

So `poetry.lock` is similar to `npm`'s `package-lock.json` or to `yarn.lock` (and to `cargo.lock` in Rust etc. etc.). In the conda universe [conda-lock](https://github.com/conda-incubator/conda-lock) is the closest equivalent. 

For more info check here:
- https://python-poetry.org/docs/basic-usage/#installing-dependencies
- https://realpython.com/dependency-management-python-poetry/#handle-poetrylock

**Comment by zacharyburnettNOAA** [comment]
ah, that makes sense! Thank you very much, I will update the lock file

**Comment by zacharyburnettNOAA** [comment]
I would recommend a squash commit to cancel out reversions and test commits

**Comment by zacharyburnett** [comment]
this should probably wait for #18 in order to use the tests

**Comment by pmav99** [comment]
Hi Zach

Merging the PRs you made is not so straightforward. Apart from expected conflicts (e.g. `poetry.lock`) the `coops` code has been written using `oitnb` instead of `black` + it has not been checked with `mypy`. Therefore, in order to merge them, we need additional commits on top of the existing ones (e.g. to silence mypy errors).

In order to resolve this in a timely fashion, I pulled your changes in my personal fork, applied the commits from all 3 PRs and added all that was necessary in order to make CI happy. The end result is here: https://github.com/pmav99/searvey/commits/coops

As you will notice,
1. You remain as the COMMIT_AUTHOR
2. I squashed the CI PR into a single commit.
3. CI is passing and the branch can be cleanly merged.

Therefore, I think that the easiest way to move forward is to merge the `coops` branch from my fork. Let me know what you think.

**Comment by zacharyburnett** [comment]
replaced by #22

**Pull request closed without merging**
