### PR TITLE
update workflows with test matrix and automatic PyPI publish on release

### PR DESCRIPTION
**Pull request by zacharyburnett**

### CODE REVIEW

**Comment by pmav99** [comment]
@zacharyburnett Combining `pytest-xdist` and `pytest-recording` seems to be causing failures. I haven't pin-pointed the exact problem, but:
```
pytest -vlx -k coops --record-mode none    # works
pytest -vlx -k coops --record-mode none -n auto    # fails
```

**Comment by pmav99** [comment]
It's a bit strange. 

We are missing this cassette `tests/cassettes/coops_test/test_coops_stations_within_region.yaml`. When we run the tests serially, even though the cassette is missing, the test is passing. When we run them concurrently the test fails. After adding the cassette, the tests pass in both modes. 

What I don't understand is why the tests were passing since we had a missing cassette.

**Comment by zacharyburnett** [comment]
ah, good catch, I spent some time trying to figure out why the tests were failing but was not able to

**Comment by pmav99** [comment]
@zacharyburnett closing this one, since I included the changes in #38

**Pull request closed without merging**
