### PR TITLE
ioc: Initial implementation

### PR DESCRIPTION
**Pull request by pmav99**

### CODE REVIEW

**Review by zacharyburnett — COMMENTED** [review]
these changes look good to me so far, I think we will have to implement some form of abstract `Station` in the future but for now it is fine to jail it to `coops.py`

**Comment by pmav99** [comment]
After this gets merged we should be able to build the docs on readthedocs, too.

**Comment by brey** [comment]
After that, we should make a release and put it on `conda-forge`.

**Review by brey — APPROVED** [review]
good to go.

**Pull request merged**
