### PR TITLE
add documentation for CO-OPS (pulled from `stormevents`)

### PR DESCRIPTION
**Pull request by zacharyburnett**

### CODE REVIEW

**Comment by brey** [comment]
@zacharyburnett I was about to do a PL for docs. We've used `mkdocs` on [`pyposeidon`](https://pyposeidon.readthedocs.io/en/latest/index.html) and worked nice . You are building with `sphinx` so there is a decision to be made here.

**Comment by zacharyburnett** [comment]
ah ok, I am fine with `mkdocs`, I was just porting over the `sphinx` docs that I had for CO-OPS from `stormevents`

**Comment by zacharyburnett** [comment]
it looks like it would be pretty simple, just a matter of porting the `*.rst` files from this PR to the markdown format used by `mkdocs`

**Comment by zacharyburnett** [comment]
also, the `coops_data.ipynb` example file links to pages at https://searvey.readthedocs.io that don't exist, but I'm okay with any hosting service that you guys are already using

**Pull request merged**
