### PR TITLE
Add high level API + various improvements

### PR DESCRIPTION
**Pull request by pmav99**
Fixes:
- #41
- #44 
- #46

### CODE REVIEW

**Review by brey — COMMENTED** [review]
Shouldn't the scripts from Carola be in a separate folder? I believe it's a bit confusing on the top tree.

**Comment by pmav99** [comment]
I haven't touched the scripts from @carolakaiser. I just run black on them so that CI could continue. I will open a separate ticket for them

**Comment by pmav99** [comment]
@zacharyburnett We could move them there, too. The reason I inlined them in `stations.py` is that `get_stations()` returns a specific subset of the available metadata. Having a function that will extract/normalize the relevant columns for each provider is something that I don't think will be useful in a different context i.e. outside of `get_stations()`. But I could be wrong.

**Comment by zacharyburnett** [comment]
> @zacharyburnett We could move them there, too. The reason I inlined them in `stations.py` is that `get_stations()` returns a specific subset of the available metadata. Having a function that will extract/normalize the relevant columns for each provider is something that I don't think will be useful in a different context i.e. outside of `get_stations()`. But I could be wrong.

No you're right, that makes sense.

**Pull request merged**
